Feature/be/jyd/user
angrydo/AggroPingPong pull request #5
Opened 2024-12-31 02:42 UTC by angrydo

## 📌 작업 개요
- merge feature/be/jyd/user to develop

### ✨ 변경사항 종류
- [ o ] 신규 기능
- [ ] 버그 수정
- [ ] 기능 삭제
- [ ] 대규모 변경
- [ ] 인프라 변경
- [ ] 문서 업데이트

### 📌 작업내용 요약
- [feature/be/jyd/user] 회원 생성 수정 삭제 기본 API 구현

## 📋 작업 상세
-

### 1. **✅ 작업 내용 (What)**
-회원 create, deleate, update
### 4. **🔗 참고 자료 (References)**
- 해당 없음

## 🧪 테스트
- 해당 없음

### 1. **테스트 추가 여부**
- 해당 없음

## 📢 추가 메모 💬
- 회원 search 기능 필요
- user entity에 enum 타입 변수 이해 못함
- user entity에 timestamp 타입 적용 못함 ex) birthday

## 🙏 요청 사항 💬
- 검토 후 승인 바람

2025-01-02 14:42 UTC, JoSihun requested changes
수정사항 변경 후 재 PR 부탁드립니다.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/domain/User.java
> +    //Role타입 import jakarta.persistence.*;-> 머임이거?
Jakrta Persistence 는 JPA 라이브러리 명임. User에서 Role은 개발자가 별도의 Role 클래스를 생성하여 사용하는 것이 일반적임.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/domain/User.java
> +    //<----수정일자
생년월일의 경우 LocalDateTime 타입, 자동갱신이 필요한 생성일자와 수정일자의 경우
Hibernate의 @CreationTimestamp와 @UpdateTimestamp 사용.

```java
    private LocalDateTime birthday;
    @CreationTimestamp
    private LocalDateTime createdDate;
    @UpdateTimestamp
    private LocalDateTime updatedDate;
```

Googling을 통해 기반지식을 쌓고, 팀 프로젝트의 코드 일관성을 위해
자신뿐만 아니라, 팀원의 코드를 살피는 습관을 기르도록 합시다.

수정 후에는 관련 Dto, Service, Controller에 변경할 사항은 없는지, 문제가 없는지 반드시 확인하도록 합니다.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/dto/UserRequestDto.java
> +public class UserRequestDto {
UserCreateRequestDto와 중복코드. 별도의 사용처가 있다면 클래스명 수정, 불필요하다면 삭제합시다.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/repository/UserRepository.java
> +    // ENTITY #설명필요!!!
불필요한 주석은 본인 Branch Commit 단계에서 물어보도록 하고, Merge 단계에서는 삭제하도록 합니다.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/repository/UserRepository.java
> +    // BOOLEAN #설명필요!!!
불필요한 주석은 본인 Branch Commit 단계에서 물어보도록 하고, Merge 단계에서는 삭제하도록 합니다.

2025-01-02 14:42 UTC, JoSihun commented on backend/src/main/java/com/skuce/aggropingpong/user/service/UserReadService.java
> +@Transactional
읽기 전용 서비스는 `@Transactional(readOnly = true)` 를 사용하도록합니다.
팀 프로젝트의 코드 일관성을 위해 자신뿐만 아니라, 팀원의 코드를 살피는 습관을 기르도록 합시다.
현 단계에서 의미있는 서비스 로직이 없으므로 해당 파일은 Commit or Merge 하지 않도록 합니다.

2025-01-04 08:19 UTC, angrydo commented on backend/src/main/java/com/skuce/aggropingpong/user/domain/User.java
> +    //<----수정일자
확인하고 수정했습니다.

2025-01-04 08:19 UTC, angrydo commented on backend/src/main/java/com/skuce/aggropingpong/user/repository/UserRepository.java
> +    // ENTITY #설명필요!!!
확인하고 수정했습니다.

2025-01-04 08:20 UTC, angrydo commented on backend/src/main/java/com/skuce/aggropingpong/user/service/UserReadService.java
> +@Transactional
확인하고 수정했습니다.

2025-01-04 08:20 UTC, angrydo commented on backend/src/main/java/com/skuce/aggropingpong/user/repository/UserRepository.java
> +    // BOOLEAN #설명필요!!!
확인하고 수정했습니다.

2025-01-04 08:32 UTC, JoSihun approved these changes

2025-01-04 08:33 UTC, merged